"use strict";
//............Question 1........................................
let fruits = ["Apple", " Banana", " Mango", " Orange "];
//............Question 2........................................
let numbers = [10, 20, 30, 40];
//............Question 3........................................
let thirdFruit = fruits[2];
//............Question 4........................................
numbers[1] = 25;
//............Question 5........................................
fruits.push("grape");
//............Question 6........................................
fruits.pop;
let lastFruit = fruits[3];
//............Question 7........................................
fruits.shift();
let firstFruit = fruits[0];
//............Question 8........................................
fruits.unshift("Kiwi");
//............Question 9........................................
fruits.slice(1, 2);
//............Question 10........................................
fruits.splice(2, 0, "Pineapple", "Pear");
//............Question 11.......................................
let citrusFruits = fruits.slice(0, 2);
//............Question 12.......................................
let lastTwoFruits = fruits.slice(-2);
